Screen Time Manager
hackclub/browserbuddy pull request #109
Opened 2024-12-24 14:52 UTC by GaoYeGithub

# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
Screen Time Manager

2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
7

3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
Monitor and control your screen time across different websites
Daily Resettable screen limits
Permanently blocked sites to help with self control
Unblock website list
Notifications nearing end of screen time

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_
2 friends and voters on high seas

5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
Yep, works on chrome not sure about firefox though.

2024-12-24 20:13 UTC, JosiasAurel requested changes

2024-12-24 20:13 UTC, JosiasAurel commented on submissions/ScreenLimits/README.md
> +# Screen Time Manager
<img width="388" alt="image" src="https://github.com/user-attachments/assets/8bb0800c-1688-4d7a-bb6a-31f1544cc013" />

How does it calculate the time spent? I've left my browser open for more than two minutes including on sites in my blocklist but it never seems to elapse?
It'll be nice to also include instructions on how to use it

2024-12-24 20:13 UTC, JosiasAurel commented on submissions/ScreenLimits/manifest.json
> +}
<img width="563" alt="image" src="https://github.com/user-attachments/assets/ef070ca4-5ff3-4f82-863b-16b060211732" />

It also appears the extension fails to load some icons

2024-12-24 20:22 UTC, GaoYeGithub commented
Are you using fire fox? I use chrome.storage.sync to check time per minutes 

https://www.loom.com/share/4d85c34d53304777b2e1d5d51a6535b1

2024-12-24 20:23 UTC, GaoYeGithub commented
Oops the icons are suppose to be in a folder lemme fix that

2024-12-24 20:29 UTC, GaoYeGithub commented
Hmm I did a bit of research and it seems Firefox will still recognize chrome.storage.sync. Is there any errors I can see?

2024-12-26 13:21 UTC, JosiasAurel requested changes
<img width="558" alt="image" src="https://github.com/user-attachments/assets/7dfdac47-ab2c-4457-89dd-dab83ad9c477" />

I'm unable to install the extension on my side. Please test and make sure the extension installs properly on Chrome-based browsers at least

2024-12-26 14:22 UTC, GaoYeGithub commented
So sorry I'm unable to reproduce the error, I didn't change any files from the beginning so I'm unsure why your experiencing this.  Maybe try removing and reinstalling? So sorry, I'm very new to chrome extensions

https://www.loom.com/share/c573639347e34f61bd27d0f3f00e53c3

2024-12-27 08:48 UTC, JosiasAurel approved these changes
Awesome! If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

2024-12-27 08:50 UTC, merged