Add YT-Direct-Search - By Asher
hackclub/browserbuddy pull request #113
Opened 2024-12-26 08:59 UTC by AsherCarneiro

# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?** > YT-Direct-Search

2. **How many hours did you spend developing this?**  > 2-4 hours maybe
   _(Give your best estimate)_

3. **What problem does your extension solve, or what makes it unique?**  
   > So the thing is i love using yt to search up everything instead of google ik but i hate going through all the slow loading of yt and then it loads at turtle's, then i have to type my query which is tedious sometimes so instead i made this, when i press ctrl shift y it brings up a kinda pretty looking search bar which autofocuses on keyboard and then you just put in your query and press enter, yes the other feature is you can select any text when browser normally and click "search that on youtube" in context menu and you're taken directly to your results.

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_ including me and i gave it to couple of my friends 4-5

5. **Does your extension work in both Chrome and Firefox?**  > Yes, it works perfectly fine with chromium-based browsers

---

## Additional Comments

(Feel free to provide any additional context or notes here)

2024-12-26 13:17 UTC, JosiasAurel requested changes
I like the concept but I think it'll be more useful if it could support more website.

Like a binding for searching Google/YT/Reddit/GitHub - you get the idea. Perhaps these bindings could be changed by the user of the extension

2024-12-26 16:55 UTC, AsherCarneiro commented
> I like the concept but I think it'll be more useful if it could support more website.
> 
> Like a binding for searching Google/YT/Reddit/GitHub - you get the idea. Perhaps these bindings could be changed by the user of the extension

hi so ive changed some stuff in latest commit, idk about user customizable binding cause i cant figure that out, but ive added options that you suggested, so now it lets you search anything using ALT + SHIFT + {Y,G,R,D} where press Y for Youtube, Reddit has R, G for Github and D for DuckDuckGo and all with their dynamically updated logo, and the other context to yt quick search remains untouched.

and ive changed the bindings to alt cause ctrl causes some conflicts in browsers.

2024-12-27 08:29 UTC, JosiasAurel approved these changes
Nice! If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

2025-01-02 19:23 UTC, closed without merging

2025-01-05 10:01 UTC, JosiasAurel commented
@AsherCarneiro why did you close the PR?