Add my High Seas Extension
hackclub/browserbuddy pull request #115
Opened 2024-12-28 22:44 UTC by DJ-Laser

# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
DJ_Laser's high Seas Tracker

2. **How many hours did you spend developing this?** 
34 hours, ik its alot but proof:
![Screenshot from 2024-12-28 17-42-57](https://github.com/user-attachments/assets/7a9e0054-d075-40f4-80dd-40927f1b5159)

4. **What problem does your extension solve, or what makes it unique?**  
Provides high seas doubloons per hour and stats while actually working on firefox unlike the existing ones on the firefox addons browser

5. **How many people have tested your extension?**  
2 people

6. **Does your extension work in both Chrome and Firefox?**  
Yup :) Manifest v3 too!

---

## Additional Comments

(Feel free to provide any additional context or notes here)

2024-12-29 20:06 UTC, JosiasAurel requested changes
@DJ-Laser please could you clearly explain why these stats are important and why one would want to use it instead of viewing their high-seas dashboard?

Also please provide an easy way of building this that does not rely on Nix (which would also mean getting rid of the `COMPILED EXTENSIONS` folder which constitutes a huge part of the diff right now).

2024-12-29 21:08 UTC, DJ-Laser commented
Idk what you mean by easy way of building, the nix just installs nodejs easier, but either way you still need node installed because it uses webpack

2024-12-29 22:27 UTC, DJ-Laser commented
> @DJ-Laser please could you clearly explain why these stats are important and why one would want to use it instead of viewing their high-seas dashboard?

Basically while the shipyard shows you the total amount of doubloons you got, it doesn't tell you how well it did compared to your other projects. Doubloons per hour helps you see which projects were the most valuable per amount of time you put in.

There are all calculated into a total average, which can be used on to estimate how long it will take to earn a certain amount of doubloons, which is calculated and put onto the shop page so you can see approximately how long it will take to get enough doubloons for an item.

It also syncs which items that you have marked as favourite so you don't have to reselect them on all your devices or redo it if your browser cache is cleared

2024-12-30 13:16 UTC, JosiasAurel requested changes

2024-12-30 13:16 UTC, JosiasAurel commented on submissions/DJ_Laser's High Seas Extension/COMPILED EXTENSIONS/high-seas-tracker-chrome-0.3.1.zip
please get rid of this

2024-12-30 13:16 UTC, JosiasAurel commented on submissions/DJ_Laser's High Seas Extension/COMPILED EXTENSIONS/high-seas-tracker-firefox-0.3.1.xpi
get rid of this too

2024-12-30 13:16 UTC, JosiasAurel commented on submissions/DJ_Laser's High Seas Extension/flake.lock
we no longer need this right? the extension builds without Nix.

2024-12-30 13:16 UTC, JosiasAurel commented on submissions/DJ_Laser's High Seas Extension/flake.nix
this too right? what is the Nix still needed for?

2024-12-30 13:17 UTC, JosiasAurel commented
I think we no longer need the `COMPILED EXTENSIONS` folder (or include pre-built extensions) given it's easier to build with npm. I'd like to merge mainly the source of this project.

2024-12-30 15:34 UTC, DJ-Laser commented on submissions/DJ_Laser's High Seas Extension/flake.nix
Does it need to be removed? its just a file, and people can use it if they have nix installed of they can use their own manual npm

2024-12-30 15:34 UTC, DJ-Laser commented on submissions/DJ_Laser's High Seas Extension/flake.nix
Does it need to be removed? its just a file, and people can use it if they have nix installed of they can use their own manual npm

2024-12-30 16:19 UTC, JosiasAurel approved these changes
I think this is good. Please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

2025-02-17 15:41 UTC, DJ-Laser commented
No merge?

2025-02-17 17:15 UTC, merged

2025-02-17 17:15 UTC, JosiasAurel commented
> No merge?

woops my bad