Added BrowserBangs
hackclub/browserbuddy pull request #123
Opened 2024-12-31 09:25 UTC by Lorenzo0111

# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
BrowserBangs

2. **How many hours did you spend developing this?**  
2

3. **What problem does your extension solve, or what makes it unique?**  
The extension makes easier and faster to search for anything by adding shortcuts to navigate to popular websites. It is unique becauuse it supports the most common search engine and not just google

4. **How many people have tested your extension?**  
3

5. **Does your extension work in both Chrome and Firefox?**  
Yes

2024-12-31 13:33 UTC, JosiasAurel requested changes
How is your extension different from [this one](https://chromewebstore.google.com/detail/bang-anywhere/ligcjmmghnamhgohlclfkcclnkghmlil) on the Chrome Web Store? Try to add something that makes it somewhat unique from the others. It could something that fits within this festive season.

2024-12-31 14:20 UTC, Lorenzo0111 commented
My extension supports chrome omnibox, works on more search engines (including yahoo which the one you linked does not) and does not forward all queries to duckduckgo. The extension you linked just redirects to duckduckgo if user query contains "!" which is a wrong approach since if i search "hello world!" it should be a normal query while that extension takes as a bang.

I think my extension is the only one that does its job in the best way

2024-12-31 16:07 UTC, JosiasAurel commented
<img width="900" alt="image" src="https://github.com/user-attachments/assets/4a70b9d6-09c8-4978-8513-72b68aeee8ad" />

2024-12-31 16:30 UTC, Lorenzo0111 commented
And? It doesn't include yahoo but as I explained it is not done well, it just redirects if the query contains a ! while mine correctly checks for valid bangs

2024-12-31 16:45 UTC, JosiasAurel requested changes
Your extension must be using Manifest V3.
<img width="579" alt="image" src="https://github.com/user-attachments/assets/8735721c-8ce1-4021-9837-7c5d0a146bcb" />

Also please add documentation in your extension for how to use the different bangs.

2024-12-31 16:46 UTC, JosiasAurel commented
> And? It doesn't include yahoo and as I explained it is not done well, it just redirects if the query contains a ! while mine correctly checks for valid bangs

Isn't that what it's supposed to do?

2024-12-31 16:51 UTC, Lorenzo0111 commented
> > And? It doesn't include yahoo and as I explained it is not done well, it just redirects if the query contains a ! while mine correctly checks for valid bangs
> 
> Isn't that what it's supposed to do?

I mean that mine does but the one you linked does not

2024-12-31 16:52 UTC, Lorenzo0111 commented
> Your extension must be using Manifest V3. <img alt="image" width="579" src="https://private-user-images.githubusercontent.com/47951376/399501614-8735721c-8ce1-4021-9837-7c5d0a146bcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NjQxODYsIm5iZiI6MTczNTY2Mzg4NiwicGF0aCI6Ii80Nzk1MTM3Ni8zOTk1MDE2MTQtODczNTcyMWMtOGNlMS00MDIxLTk4MzctN2M1ZDBhMTQ2YmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE2NTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZWQwMzQ2OGZiZGVlMjFmMGViZDA1NGViMTkzNGQ3OWNlNjM3YjEwYzljZTQ2MGQ5ODNiNzRmMGU4NTVkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aFBqlq8B45qxVhkkhJHSkGfo6nrvFzs8WlfT69x03Ak">
> 
> Also please add documentation in your extension for how to use the different bangs.

Where should the documentation be? I put it in the README

2024-12-31 16:53 UTC, JosiasAurel commented
> > > And? It doesn't include yahoo and as I explained it is not done well, it just redirects if the query contains a ! while mine correctly checks for valid bangs
> > 
> > 
> > Isn't that what it's supposed to do?
> 
> I mean that mine does but the one you linked does not

Just a single additional bang doesn't make such a huge difference does it?

2024-12-31 16:54 UTC, JosiasAurel commented
> > Your extension must be using Manifest V3. <img alt="image" width="579" src="https://private-user-images.githubusercontent.com/47951376/399501614-8735721c-8ce1-4021-9837-7c5d0a146bcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NjQxODYsIm5iZiI6MTczNTY2Mzg4NiwicGF0aCI6Ii80Nzk1MTM3Ni8zOTk1MDE2MTQtODczNTcyMWMtOGNlMS00MDIxLTk4MzctN2M1ZDBhMTQ2YmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE2NTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZWQwMzQ2OGZiZGVlMjFmMGViZDA1NGViMTkzNGQ3OWNlNjM3YjEwYzljZTQ2MGQ5ODNiNzRmMGU4NTVkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aFBqlq8B45qxVhkkhJHSkGfo6nrvFzs8WlfT69x03Ak">
> > Also please add documentation in your extension for how to use the different bangs.
> 
> Where should the documentation be? I put it in the README

Both in the readme and examples in the extension so new users can easily pick it up.

2024-12-31 16:54 UTC, Lorenzo0111 commented
I mean the search engine, not the bang. You can't use bangs in yahoo with that extension. But the main issue that I think makes my extension different is that it works well compared to the other one

2024-12-31 16:55 UTC, JosiasAurel commented
> I mean the search engine, not the bang. You can't use bangs in yahoo with that extension. But the main issue that I think makes my extension different is that it works well compared to the other one

Yours works in all search engines? Cool!

2024-12-31 16:57 UTC, Lorenzo0111 commented
> > I mean the search engine, not the bang. You can't use bangs in yahoo with that extension. But the main issue that I think makes my extension different is that it works well compared to the other one
> 
> Yours works in all search engines? Cool!

Not all but the most popular. It's impossible sadly to support all due to manifest regulations

2024-12-31 16:58 UTC, JosiasAurel commented
> > > I mean the search engine, not the bang. You can't use bangs in yahoo with that extension. But the main issue that I think makes my extension different is that it works well compared to the other one
> > 
> > 
> > Yours works in all search engines? Cool!
> 
> Not all but the most popular. It's impossible sadly to support all due to manifest regulations

I see... that's alright

2025-01-01 10:03 UTC, Lorenzo0111 commented
I think I applied all the fixes

2025-01-01 13:39 UTC, Lorenzo0111 commented
> > And? It doesn't include yahoo and as I explained it is not done well, it just redirects if the query contains a ! while mine correctly checks for valid bangs
> 
> 
> 
> Isn't that what it's supposed to do?

I think I read this wrong first time apologies, what I meant is that the goal of the extension is to detect if the query has a bang (example: "hello world !yt" redirects to youtube etc). This is done by using a big dictionary of bangs that explain for each bang the url it redirects to. What that extension does is to redirect all queries to duckduckgo if they contain a "!" so that it will handle the bang for them. It's a big difference because if the user types a wrong bang or just a normal exclamation mark, it should not redirect since it's not a bang. My extension handles it correctly by parsing bangs from the duckduckgo dictionary, that extension, on the other hand, always redirects user to duckduckgo if query has a "!"

I hope this explains better why I chose to build my own

2025-01-01 15:13 UTC, JosiasAurel commented
For some reason it first goes to Google Search results before redirecting to the appropriate file with the query entered. Why is that?

https://github.com/user-attachments/assets/2b1b1767-f894-4d5b-b0af-4ff0365db1ab

2025-01-01 15:20 UTC, Lorenzo0111 commented
Sadly manifest v3 removed webRequestBlocking so this seems to be the easier way to handle the redirect

2025-01-01 15:51 UTC, JosiasAurel approved these changes
Please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

2025-01-01 15:52 UTC, Lorenzo0111 commented
> lease fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

Thank you! I've already filled it

2025-01-01 15:58 UTC, merged