Submission for Browser buddy
hackclub/browserbuddy pull request #43
Opened 2024-10-27 09:57 UTC by crabby605

my extension Cat-follow-mouse-real adds a cat on every webpage that can be pet and it follows ur mouse!!!

2024-10-28 11:55 UTC, JosiasAurel requested changes
Please create something of your own or you need to make significant changes or add new features to what you currently have here.

2024-10-28 11:55 UTC, JosiasAurel commented on submissions/cat-folloe-mouse-real/catFollowMouse.js
> +(function oneko() {
This is clearly a copy of [oneko.js](https://github.com/adryd325/oneko.js/blob/main/oneko.js). Copying other people's work is not acceptable.

2024-10-28 13:18 UTC, crabby605 commented
> Please create something of your own or you need to make significant changes or add new features to what you currently have here. 

I actually did mention that this uses oneko I nade it as a extension and added the petting function I'll add more if that's not enough

2024-11-19 08:40 UTC, JosiasAurel commented
closing due to inactivity

2024-11-19 08:40 UTC, closed without merging