Add files via upload
hackclub/browserbuddy pull request #55
Opened 2024-11-08 04:42 UTC by CoderLogy

### Project Details
1. **What is the name of your project?**

    **Tabs-Counter**

2. **How many hours did you spend developing this?**  

    **Spent Around 2 hours on this.**

3. **What problem does your extension solve, or what makes it unique?**  

     **I was facing problems of having to know how many tabs I have open in current browser but there was no easy and intuitive way to know about it and therefore I thought to make this project because not knowing and closing important tabs made me really mad, I hope this will cure that problem.**

4. **How many people have tested your extension?**  
   
    **Right now I have tested this on two different browser Edge and Firefox and hoping for others to test this.**

5. **Does your extension work in both Chrome and Firefox?**  

    **Yes it works on both the browsers.**

---

2024-11-09 04:25 UTC, CoderLogy commented
@JosiasAurel , please look into this

2024-11-11 05:55 UTC, JosiasAurel requested changes
Please restore the files you deleted. Also this browser extension is not unique and I'm not sure how it's going to stop you from closing important tabs given it just shows the number of open tabs.

2024-11-11 05:55 UTC, JosiasAurel commented on website/public/DaviLhlapakRosa_business_dino.png
why did you delete this file? it's part of the website source code

2024-11-11 05:55 UTC, JosiasAurel commented on submission/Tabs-Counter/chrome/popup.js
How's this project unique? There are plenty other tab counter extensions out there!

2024-11-11 05:59 UTC, CoderLogy commented
What files are you asking about and why it is not unique. I had the problem of running out of memory of my computer when using browser as I couldn't stop myself from opening so many tabs. It helps right.

2024-11-11 06:11 UTC, JosiasAurel commented
It's not clear to me how this extension prevents you from opening new tabs and running out of memory. 
If you look under the "Files Changed" tab on this pull request there are a few files that have been deleted but that shouldn't have.

2024-11-11 08:45 UTC, CoderLogy commented on website/public/DaviLhlapakRosa_business_dino.png
I didn't delete any file all I did was to sync it to the parent repo and any files deleted was by the parent repo not mine. I just synced the changes.

2024-11-11 15:27 UTC, JosiasAurel commented on website/public/DaviLhlapakRosa_business_dino.png
In that case please rebase your local copy

2024-11-19 09:00 UTC, JosiasAurel commented
Ping here. Any updates?

2024-11-19 09:13 UTC, CoderLogy commented
Yeah just working on it, don’t have much time to do dedicate to update it.On Nov 19, 2024, at 1:01 AM, Josias ***@***.***> wrote:﻿
Ping here. Any updates?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-19 09:16 UTC, JosiasAurel commented
> Yeah just working on it, don’t have much time to do dedicate to update it.On Nov 19, 2024, at 1:01 AM, Josias ***@***.***> wrote:﻿ Ping here. Any updates? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

No pb. Please try to complete it. If you think you won't be able to go ahead with this, you can close the pull request.

2024-11-25 14:29 UTC, JosiasAurel commented
Ping! Deadline is Nov 30

2024-12-01 08:27 UTC, JosiasAurel commented
Closing due to inactivity and we're past deadline.

2024-12-01 08:27 UTC, closed without merging