Create Motivator Task Management
hackclub/browserbuddy pull request #57
Opened 2024-11-11 22:12 UTC by RobertoEchCCHS

### Project Details
1. **What is the name of your project?**

2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_

3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_

5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_

---

### Additional Comments
(Feel free to provide any additional context or notes here)

2024-11-11 22:13 UTC, RobertoEchCCHS commented
Manifest.json

{
   "manifest_version": 3,
   "name": "Motivational Dashboard",
   "version": "1.0",
   "description": "A simple motivational dashboard for daily inspiration and task management.",
   "permissions": ["storage"],
   "action": {
     "default_popup": "index.html"
   }
 }

2024-11-12 06:32 UTC, JosiasAurel requested changes

2024-11-12 06:32 UTC, JosiasAurel commented on submission/Motivator Task Management
> +
you need to include the source code in the pull request

2024-11-19 09:01 UTC, JosiasAurel commented
Ping here. Any updates?

2024-11-19 09:02 UTC, closed without merging