Add Focus Flow
hackclub/browserbuddy pull request #98
Opened 2024-12-01 02:52 UTC by pranavbehal

# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
2. Focus Flow

3. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
15-20 hours.

4. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
This extension is a website blocker to boost your productivity, but it uses AI to block websites, rather than just having a static list of sites to block/not block. In the past, I tried using basic site blockers to reduce distractions, but they were always easy to take advantage of. I made this so that AI can dynamically let you use websites that align with a task you set to complete during a session (with a Pomodoro timer), which helps boost your productivity and reduce distractions. If the AI does make a mistake, you always have the option to make an appeal to access a website. From my testing, I've seen that my AI prompt usually makes the right decision on the first try (without an appeal).

5. **How many people have tested your extension?**  
   _(We recommend at least 3)_
7 people.

6. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
My extension works on Chrome & Edge, but I haven't tested Firefox as I don't have it. However, my extension's version is Manifest 3.

---

## Additional Comments
Here is a demo video I made (I remember reading somewhere that we needed one, but I wasn't sure and made one anyways):
[](https://drive.google.com/file/d/1ZEErvjxo0wj5tDVqKNM54SptbaOgdQGc/view?usp=sharing
)
**Also, in order to use the extension, you must add your own OpenAI API key in the api-key.js file.**

2024-12-01 08:19 UTC, JosiasAurel requested changes
Please add an option to set the OpenAI API key in the extension along with instructions on how to get one. Otherwise I think this is a cool extension.

Also please add your extensions in the `submissions` folder.

2024-12-01 08:19 UTC, JosiasAurel commented on focus-flow/api-key.js
end users won't be able to modify the source code of the extension once published. you should add an interface in the extension where users can set their OpenAI API Key

2024-12-01 16:09 UTC, pranavbehal commented on focus-flow/api-key.js
I made another commit so that you can add your own API key in the "Settings' tab of the extension, please take a look.

2024-12-02 06:08 UTC, JosiasAurel approved these changes
Awesome! If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

2024-12-02 06:08 UTC, merged